const profile = {
  name: "Dr. Akesha Horton",
  initials: "AH",
  eyebrow: "Interactive tools & resources",
  headline: "Built with curiosity, designed to teach.",
  role: "Director of Academic Engagement, IU Luddy School",
  focus: "AI-built tools for educators, coaches, and curious learners",
  bio: "A collection of interactive tools built using AI for educators, coaches, researchers, and anyone who thinks learning should be smarter than a slide deck.",
  stats: [
    { label: "Tools", value: "32" },
    { label: "Focus", value: "Teaching" },
    { label: "Built with", value: "AI" },
  ],
  links: [
    {
      label: "Substack",
      url: "https://akesha.substack.com/",
      text: "Writing on teaching, learning, and academic life.",
    },
    {
      label: "Luddy @ IU",
      url: "https://blogs.iu.edu/luddyteach",
      text: "Academic engagement at the Luddy School of Informatics, Computing, and Engineering.",
    },
    {
      label: "Current portfolio",
      url: "https://akesha.github.io/portfolio/",
      text: "The live portfolio that inspired this interactive version.",
    },
  ],
};

const tools = [
  {
    id: "cs-faculty-hub",
    title: "CS Faculty Hub",
    category: "Faculty Development",
    url: "https://akesha.github.io/cs-faculty-hub/",
    image: "./assets/current/01.png",
    summary:
      "Evidence-based teaching strategies curated for computing and STEM educators, including course design, assessment, AI integration, and more.",
    tags: ["Computing education", "Teaching strategy", "STEM"],
    audience: "Faculty",
    format: "Resource hub",
  },
  {
    id: "luddyteach-retrospective",
    title: "LuddyTeach Retrospective",
    category: "Data & Analytics",
    url: "https://akesha.github.io/luddyteach-retrospective/",
    image: "./assets/current/02.png",
    summary:
      "A data-driven interactive retrospective of the LuddyTeach blog, surfacing patterns, themes, and insights across posts over time.",
    tags: ["Blog analytics", "Themes", "Retrospective"],
    audience: "Faculty developers",
    format: "Interactive report",
  },
  {
    id: "linkedinotprivate",
    title: "LinkedINotPrivate",
    category: "Privacy & Policy",
    url: "https://akesha.github.io/LinkedINotPrivate/",
    image: "./assets/current/03.png",
    summary:
      "An interactive guide to state data privacy laws, searchable by state, sector, and regulation type.",
    tags: ["Privacy", "Policy", "Search"],
    audience: "Professionals",
    format: "Policy guide",
  },
  {
    id: "strengths-faculty-guide",
    title: "A Faculty Guide to Strengths-Based Education",
    category: "Coaching & Strengths",
    url: "https://akesha.github.io/cliftonstrengthsinfo/",
    image: "./assets/current/04.png",
    summary:
      "An interactive guide to the 34 CliftonStrengths themes, designed to support coaches and learners preparing for certification.",
    tags: ["CliftonStrengths", "Coaching", "Certification"],
    audience: "Coaches",
    format: "Theme guide",
  },
  {
    id: "cliftonstrengths-hub",
    title: "CliftonStrengths Learning Hub",
    category: "Coaching & Strengths",
    url: "https://pages.github.iu.edu/akmhorto/cliftonstrengths-hub/",
    image: "./assets/current/05.png",
    summary:
      "A comprehensive hub for CliftonStrengths resources at IU Luddy, including theme profiles, coaching frameworks, and team strengths tools.",
    tags: ["Strengths", "Teams", "IU Luddy"],
    audience: "Luddy community",
    format: "Learning hub",
  },
  {
    id: "finks-blooms",
    title: "Fink's & Bloom's Taxonomy",
    category: "Curriculum Design",
    url: "https://akesha.github.io/visibleLearning/",
    image: "./assets/current/06.png",
    summary:
      "Side-by-side comparisons of two foundational learning taxonomies for aligning course objectives with meaningful outcomes.",
    tags: ["Bloom's", "Fink's", "Objectives"],
    audience: "Educators",
    format: "Comparison tool",
  },
  {
    id: "thinking-visible",
    title: "Making Thinking Visible: Ritchhart + Fink for STEM",
    category: "Curriculum Design",
    url: "https://akesha.github.io/visibleLearning/thinking-fink-visual.html",
    image: "./assets/current/07.png",
    summary:
      "An interactive visual combining Ron Ritchhart's Making Thinking Visible framework with Fink's Taxonomy for STEM faculty.",
    tags: ["Visible thinking", "STEM", "Taxonomy"],
    audience: "STEM faculty",
    format: "Visual guide",
  },
  {
    id: "beyond-blooms-fink-computing",
    title: "Beyond Bloom's: Fink's Taxonomy for Computing",
    category: "Curriculum Design",
    url: "https://pages.github.iu.edu/akmhorto/computing-verb-atlas/beyond-blooms-finks-taxonomy.html",
    image: "./assets/current/08.png",
    summary:
      "A companion piece exploring what Fink's Taxonomy of Significant Learning means for computing courses and CS educators.",
    tags: ["Computing", "Learning design", "Taxonomy"],
    audience: "CS educators",
    format: "Companion guide",
  },
  {
    id: "data-storytelling",
    title: "Data Storytelling & Visualization Resource Portal",
    category: "Data & Visualization",
    url: "https://akesha.github.io/data-storytelling-resources/",
    image: "./assets/current/09.png",
    summary:
      "A curated portal of resources for teaching and learning data storytelling, with tools, readings, activities, and frameworks.",
    tags: ["Data storytelling", "Visualization", "Resources"],
    audience: "Educators",
    format: "Resource portal",
  },
  {
    id: "power-bi-qualitative",
    title: "Power BI Qualitative Data Visualization Guide",
    category: "Data & Visualization",
    url: "https://akesha.github.io/PowerBI/powerbi-qualitative-guide.html",
    image: "./assets/current/10.png",
    summary:
      "An interactive guide for visualizing qualitative research data in Power BI and moving beyond spreadsheets into visual analysis.",
    tags: ["Power BI", "Qualitative data", "Research"],
    audience: "Researchers",
    format: "Guide",
  },
  {
    id: "nsf-logic-model",
    title: "NSF Logic Model Builder",
    category: "Research & Funding",
    url: "https://huggingface.co/spaces/drakesha/nsf-logic-model-builder",
    image: "./assets/current/11.png",
    summary:
      "An AI-powered tool for building NSF grant logic models that map inputs, activities, outputs, and outcomes.",
    tags: ["NSF", "Logic models", "Grant writing"],
    audience: "Researchers",
    format: "AI builder",
  },
  {
    id: "ai-teaching-resources",
    title: "AI Teaching Resources for Faculty in Technical Fields",
    category: "AI & EdTech",
    url: "https://www.playlab.ai/project/cmhtkrsv4ba9rml0ufwxhysbg",
    image: "./assets/current/12.png",
    summary:
      "A curated AI-powered tool helping faculty in CS, engineering, informatics, and library science discover relevant AI tools.",
    tags: ["AI tools", "Technical fields", "Teaching"],
    audience: "Technical faculty",
    format: "AI resource finder",
  },
  {
    id: "strengths-prompts",
    title: "Strengths Coaching Prompt Lab",
    category: "Coaching & Strengths",
    url: "https://akesha.github.io/strengths-prompts/",
    image: "./assets/current/13.png",
    summary:
      "An interactive prompt generator for CliftonStrengths coaching conversations with targeted, theme-specific questions.",
    tags: ["Prompts", "Coaching", "CliftonStrengths"],
    audience: "Coaches",
    format: "Prompt lab",
  },
  {
    id: "taxonomy-verb-finder",
    title: "Taxonomy Verb Finder: Bloom's + Fink's",
    category: "Curriculum Design",
    url: "https://akesha.github.io/beyondBlooms/",
    image: "./assets/current/15.png",
    summary:
      "A searchable tool for matching action verbs to Bloom's and Fink's taxonomy levels for stronger learning objectives.",
    tags: ["Action verbs", "Objectives", "Taxonomies"],
    audience: "Educators",
    format: "Finder",
  },
  {
    id: "faculty-onboarding",
    title: "Faculty Onboarding System",
    category: "Faculty Development",
    url: "https://ai-build-lab-1.onrender.com/login",
    image: "./assets/current/16.png",
    summary:
      "A quick pre-interview system for discovering faculty onboarding needs before meeting with a faculty developer.",
    tags: ["Onboarding", "Needs assessment", "Faculty support"],
    audience: "New faculty",
    format: "Intake system",
  },
  {
    id: "grant-finder",
    title: "Grant Finder & Tracker",
    category: "Research & Funding",
    url: "https://akesha.github.io/photoalbum/grant-finder.html",
    image: "./assets/current/14.png",
    summary:
      "A searchable dashboard for finding, filtering, and tracking grant opportunities across education, HCI, arts, makerspaces, and more.",
    tags: ["Grants", "Funding", "Tracker"],
    audience: "Researchers",
    format: "Dashboard",
  },
  {
    id: "syllabus-quest",
    title: "Syllabus Quest",
    category: "Faculty Development",
    url: "https://akesha.github.io/edugame/",
    image: "./assets/current/17.png",
    summary:
      "An interactive video game that helps students understand syllabus policies and university resources for an undergraduate research course.",
    tags: ["Game", "Syllabus", "Student success"],
    audience: "Students",
    format: "Learning game",
  },
  {
    id: "meal-planner",
    title: "Meal Planner",
    category: "Lifestyle & Productivity",
    url: "https://akesha.github.io/dinner-picker/",
    image: "./assets/current/18.png",
    summary:
      "An interactive tool for planning healthy, balanced meals throughout the week for a busy or low-energy lifestyle.",
    tags: ["Meal planning", "Wellness", "Productivity"],
    audience: "Busy people",
    format: "Planner",
  },
  {
    id: "digital-storytelling",
    title: "Digital Storytelling for Faculty",
    category: "Faculty Development",
    url: "https://akesha.github.io/completestory/",
    image: "./assets/current/19.png",
    summary:
      "An interactive page that helps faculty teach students to create digital stories using media, narration, and visual storytelling tools.",
    tags: ["Digital storytelling", "Media", "Faculty"],
    audience: "Faculty",
    format: "Teaching guide",
  },
  {
    id: "instructional-reflection",
    title: "Instructional Reflection Tool",
    category: "Faculty Development",
    url: "https://instructional-reflection.vercel.app/",
    image: "./assets/current/20.jpeg",
    summary:
      "A structured end-of-term protocol for turning teaching observations into evidence, dossier material, or a SoTL project.",
    tags: ["Reflection", "SoTL", "Teaching dossier"],
    audience: "Faculty",
    format: "Reflection protocol",
  },
  {
    id: "github-playground",
    title: "GitHub Playground",
    category: "Faculty Development",
    url: "https://akesha.github.io/git-playground/playground/",
    image: "./assets/current/21.png",
    summary:
      "An interactive playground for learning Git and GitHub concepts hands-on without fear of breaking anything.",
    tags: ["GitHub", "Version control", "Practice"],
    audience: "Students and faculty",
    format: "Practice playground",
  },
  {
    id: "word-problems",
    title: "Word Problems",
    category: "EdTech & Math",
    url: "https://akesha.github.io/wordproblems/sources/",
    image: "./assets/current/22.png",
    summary:
      "A web-based workbook that helps high school and college students slow down and interpret a math word problem instead of pattern-matching their way to an answer.",
    tags: ["Math", "Word problems", "Student reasoning"],
    audience: "High school and college students",
    format: "Workbook",
  },
  {
    id: "journey-map",
    title: "My Journey Map",
    category: "Personal & Narrative",
    url: "https://akesha.github.io/journeymap/",
    image: "./assets/current/23.png",
    summary:
      "A single-file interactive scrollytelling map of twelve chapters across work, learning, and personal life, with each chapter revealing one scene at a time.",
    tags: ["Scrollytelling", "Narrative", "Journey map"],
    audience: "Readers",
    format: "Interactive story",
  },
  {
    id: "student-ai-literacy-sandbox",
    title: "Student AI Literacy Sandbox",
    category: "AI & EdTech",
    url: "https://akesha.github.io/homework/",
    image: "./assets/current/24.png",
    summary:
      "A 50-minute faculty workshop and design studio teaching students to argue with AI before they trust it.",
    tags: ["AI literacy", "Workshop", "Student judgment"],
    audience: "Faculty and students",
    format: "Workshop sandbox",
  },
  {
    id: "student-ai-literacy-structured-use",
    title: "Student AI Literacy Through Structured Use",
    category: "AI & EdTech",
    url: "https://akesha.github.io/dail/",
    image: "./assets/current/25.png",
    summary:
      "A browser-based activity that guides learners through answering first, prompting deliberately, critiquing AI output, revising, and exporting an AI Use Note.",
    tags: ["AI literacy", "Structured use", "Student reflection"],
    audience: "Students and faculty",
    format: "Guided activity",
  },
  {
    id: "algebra-invaders",
    title: "Algebra Invaders",
    category: "EdTech & Math",
    url: "https://akesha.github.io/mathgame/",
    image: "./assets/current/26.jpeg",
    summary:
      "A retro arcade-style math game that helps learners practice algebra and math facts through fast, playful problem solving.",
    tags: ["Algebra", "Math practice", "Game-based learning"],
    audience: "Students",
    format: "Learning game",
  },
  {
    id: "wherefore-civic-reasoning",
    title: "Wherefore: A Civic Reasoning Quest",
    category: "Civic & Legal Education",
    url: "https://akesha.github.io/wherefore/design/",
    image: "./assets/current/27.png",
    summary:
      "An AI-scaffolded web app that teaches constitutional reasoning through a 6-station quest, with each station focused on one doctrine.",
    tags: ["Civic reasoning", "Constitutional law", "AI scaffold"],
    audience: "High school and college students",
    format: "Quest-based web app",
  },
  {
    id: "blog-to-video-workshop",
    title: "From Blog Post to Animated Video · A Workshop Guide",
    category: "AI & EdTech",
    url: "https://akesha.github.io/aiquickvideo/",
    image: "./assets/current/28.png",
    summary:
      "A single-page workshop guide that walks writers and artists through turning a blog post into a 30-second animated video with Runway, ElevenLabs, CapCut, and optionally Invideo AI. Eight sequential scenes framed by pre-scene principles, watch-outs, and a resources toolkit.",
    tags: ["AI video", "Workshop", "Content creation"],
    audience: "Writers and artists",
    format: "Workshop guide",
  },
  {
    id: "teaching-at-luddy",
    title: "Teaching at Luddy",
    category: "Faculty Development",
    url: "https://akesha.github.io/facultyresource/",
    image: "./assets/current/29.png",
    summary:
      "A field guide for Luddy faculty, built around student-centered design, a shared teaching vocabulary, and one-on-one support. A searchable Q&A catalog covers inherited syllabi, first-semester checklists, redesign strategy, AI policy, and school-specific acronyms — designed so faculty can find the one answer they need without reading the whole thing.",
    tags: ["Faculty resource", "Course design", "IU Luddy"],
    audience: "Luddy faculty",
    format: "Field guide",
  },
  {
    id: "veiled-tarot",
    title: "Veiled · A Tarot Practice",
    category: "Reflective Practice",
    url: "https://veiled-tarot.pages.dev/",
    image: "./assets/current/30.png",
    summary:
      "An interactive tarot reading site framed as a contemplative practice rather than fortune-telling. Users bring a question, shuffle and cut a 78-card deck, and receive a personal reading built around the cards' historical meanings. A three-step ritual — bring the question, shuffle & cut, read & reflect — designed as journaling scaffolding, not prophecy.",
    tags: ["Contemplative", "Journaling", "Ritual design"],
    audience: "Adults sitting with a question",
    format: "Interactive reading",
  },
  {
    id: "role-play-practice",
    title: "Role Play Practice · Intelligent Systems Engineering",
    category: "AI & EdTech",
    url: "https://akesha.github.io/scenario/",
    image: "./assets/current/31.png",
    summary:
      "An AI-powered role play tool for ISE students to rehearse the workplace conversations engineers actually have. Users describe a scenario or pick from a bank of ~32 ready-made role plays across eight categories: stakeholder communication, requirements elicitation, defending design decisions, failure modes, technical interviews, professionalism, negotiation, and teammate disagreements. Sandboxed — conversations aren't saved.",
    tags: ["Soft skills", "AI role play", "Career readiness"],
    audience: "ISE students",
    format: "AI practice tool",
  },
  {
    id: "git-playground",
    title: "Git Playground",
    category: "Faculty Development",
    url: "https://akesha.github.io/git-playground/",
    image: "./assets/current/32.png",
    summary:
      "An in-browser simulator that makes Git's invisible state model visible. Type real Git commands and watch files travel between the working directory, staging area, local commits, and remote — a hands-on way to build the mental model behind add, commit, and push.",
    tags: ["Git", "Simulator", "Version control"],
    audience: "Students and faculty",
    format: "Interactive simulator",
  },
];

const capabilities = [
  {
    title: "Tools That Teach",
    text: "The archive turns complex educational ideas into objects people can touch: hubs, dashboards, prompt labs, games, and guided workflows.",
  },
  {
    title: "AI As a Making Partner",
    text: "The work treats AI as a way to build faster, test ideas in public, and create practical resources for faculty development.",
  },
  {
    title: "Faculty-Centered Design",
    text: "Most tools start from a real teaching, coaching, or academic support need and make the next step easier to see.",
  },
];

const playbook = [
  {
    id: "teach",
    label: "Teach",
    title: "Make the invisible parts of learning visible.",
    text: "Many tools help educators move from broad teaching ideas to concrete objectives, prompts, activities, and resources.",
    points: [
      "Translate theory into usable teaching moves.",
      "Give faculty a clear starting point instead of a blank page.",
      "Keep resources practical enough to use between meetings.",
    ],
  },
  {
    id: "coach",
    label: "Coach",
    title: "Create prompts that invite reflection.",
    text: "The strengths and reflection tools are built around better questions, helping people notice patterns and name next steps.",
    points: [
      "Support self-awareness without flattening people into labels.",
      "Turn themes and incidents into conversation starters.",
      "Make coaching materials easier to adapt in the moment.",
    ],
  },
  {
    id: "research",
    label: "Research",
    title: "Help researchers organize evidence and opportunity.",
    text: "The data, funding, and reporting tools create structure around analysis, grant planning, and decision-making.",
    points: [
      "Surface patterns across qualitative and quantitative material.",
      "Support grant planning with clearer models and tracking.",
      "Make dashboards and guides approachable for non-specialists.",
    ],
  },
];

window.portfolioData = {
  capabilities,
  playbook,
  profile,
  tools,
};
